name: texnopolis
description: "Texnopolis cine app redesigned"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  url_launcher: ^6.3.1
  intl: any
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.svg

  fonts:
    - family: Manrope
      fonts:
        - asset: assets\fonts\Manrope-ExtraLight.ttf
          weight: 100
        - asset: assets\fonts\Manrope-Light.ttf
          weight: 200
        - asset: assets\fonts\Manrope-Medium.ttf
          weight: 300
        - asset: assets\fonts\Manrope-Regular.ttf
          weight: 400
        - asset: assets\fonts\Manrope-SemiBold.ttf
          weight: 500
        - asset: assets\fonts\Manrope-Bold.ttf
          weight: 600
        - asset: assets\fonts\Manrope-ExtraBold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
#  image_path: "assets/logo_white.png"
  image_path: "assets/logo_green.png"